version: '3.9'
services:
  loadbalancer:
    build: ./loadbalancer
    image: loadbalancer
    container_name: loadbalancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    # depends_on:
    #   - server
    networks:
      network1:
        aliases: 
          - loadbalancer
    environment:
      VAR1 : Value1

  

  # server:
  #   build: ./server
  #   image: server
  #   container_name: server
  #   networks:
  #     network1:
  #       aliases: 
  #         - server
  #   # #environment:
    #   PERSIST : ${PERSISTENCE_MODE}
    #   SID : server0

networks:
  network1:
    name: net1
    
    
